    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">ZFBase</a>
          <div class="nav-collapse">
<?php 
$this->navigation()->menu()->setUlClass('nav');
echo $this->navigation()->menu()->render();
?>
          </div>
        </div>
      </div>
    </div>